### ISSUE TITLE
ifografia

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/actividad-1-infografia-EdgarExa#1]
[Infografia2.pdf](https://github.com/user-attachments/files/16852094/Infografia2.pdf)

edgar axel sandoval hernandez

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenos días compañero, excelente trabajo.
Porcentaje obtenido en base a la rúbrica: 20%.

**Comment by josealfredo79** [comment]
bien hecho y revisado..
